FROM apache/airflow:2.7.1

USER root

# Instala dependências do sistema
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Copia o requirements.txt
COPY requirements.txt /opt/airflow/requirements.txt

# Instala as dependências Python
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt 